services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./separated_videos:/app/separated_videos
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped
